import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const dmSans = localFont({
  src: '../fonts/DMSans.ttf',
  variable: '--font-dm-sans',
});

const cormorant = localFont({
  src: '../fonts/CormorantGaramond.ttf',
  variable: '--font-cormorant',
});

export const metadata: Metadata = {
  title: 'Frilic',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${cormorant.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
